# Generated by Django 3.2 on 2021-04-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210419_1746'),
    ]

    operations = [
        migrations.DeleteModel(
            name='produits',
        ),
        migrations.AddField(
            model_name='produit',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=6),
            preserve_default=False,
        ),
    ]
