# Generated by Django 3.2 on 2021-05-26 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_commande'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produit',
            options={},
        ),
    ]
